version: 2
jobs:
  lint:
    docker:
      - image: alangh/emacs:cask-0.8.4
    steps:
      - checkout
      - run: make lint
  test:
    docker:
      - image: alangh/emacs:cask-0.8.4
    steps:
      - checkout
    - run: make test
workflows:
  version: 2
  lint_and_test:
    jobs:
      - lint
      - test
